export const globalUniversities = [
  {
    name: 'University of Toronto',
    country: 'Canada',
    city: 'Toronto, ON',
    domains: ['utoronto.ca'],
    web_pages: ['https://www.utoronto.ca/'],
    ranking: 1,
    tuition: 32000,
  },
  {
    name: 'University of British Columbia',
    country: 'Canada',
    city: 'Vancouver, BC',
    domains: ['ubc.ca'],
    web_pages: ['https://www.ubc.ca/'],
    ranking: 2,
    tuition: 30000,
  },
  {
    name: 'McGill University',
    country: 'Canada',
    city: 'Montreal, QC',
    domains: ['mcgill.ca'],
    web_pages: ['https://www.mcgill.ca/'],
    ranking: 3,
    tuition: 28000,
  },
  {
    name: 'University of Melbourne',
    country: 'Australia',
    city: 'Melbourne, VIC',
    domains: ['unimelb.edu.au'],
    web_pages: ['https://www.unimelb.edu.au/'],
    ranking: 1,
    tuition: 45000,
  },
  {
    name: 'University of Sydney',
    country: 'Australia',
    city: 'Sydney, NSW',
    domains: ['sydney.edu.au'],
    web_pages: ['https://www.sydney.edu.au/'],
    ranking: 2,
    tuition: 47000,
  },
  {
    name: 'Australian National University',
    country: 'Australia',
    city: 'Canberra, ACT',
    domains: ['anu.edu.au'],
    web_pages: ['https://www.anu.edu.au/'],
    ranking: 3,
    tuition: 42000,
  },
  {
    name: 'ETH Zurich',
    country: 'Switzerland',
    city: 'Zurich',
    domains: ['ethz.ch'],
    web_pages: ['https://ethz.ch/en.html'],
    ranking: 1,
    tuition: 1500,
  },
  {
    name: 'Technical University of Munich',
    country: 'Germany',
    city: 'Munich',
    domains: ['tum.de'],
    web_pages: ['https://www.tum.de/en/'],
    ranking: 1,
    tuition: 0,
  },
  {
    name: 'University of Amsterdam',
    country: 'Netherlands',
    city: 'Amsterdam',
    domains: ['uva.nl'],
    web_pages: ['https://www.uva.nl/en'],
    ranking: 1,
    tuition: 12000,
  },
  {
    name: 'Sorbonne University',
    country: 'France',
    city: 'Paris',
    domains: ['sorbonne-universite.fr'],
    web_pages: ['https://www.sorbonne-universite.fr/en'],
    ranking: 1,
    tuition: 3000,
  },
  {
    name: 'National University of Singapore',
    country: 'Singapore',
    city: 'Singapore',
    domains: ['nus.edu.sg'],
    web_pages: ['https://www.nus.edu.sg/'],
    ranking: 1,
    tuition: 38000,
  },
  {
    name: 'University of Tokyo',
    country: 'Japan',
    city: 'Tokyo',
    domains: ['u-tokyo.ac.jp'],
    web_pages: ['https://www.u-tokyo.ac.jp/en/'],
    ranking: 1,
    tuition: 25000,
  },
  {
    name: 'Peking University',
    country: 'China',
    city: 'Beijing',
    domains: ['pku.edu.cn'],
    web_pages: ['https://english.pku.edu.cn/'],
    ranking: 1,
    tuition: 15000,
  },
  {
    name: 'Seoul National University',
    country: 'South Korea',
    city: 'Seoul',
    domains: ['snu.ac.kr'],
    web_pages: ['https://en.snu.ac.kr/'],
    ranking: 1,
    tuition: 12000,
  },
  {
    name: 'Indian Institute of Technology Bombay',
    country: 'India',
    city: 'Mumbai',
    domains: ['iitb.ac.in'],
    web_pages: ['https://www.iitb.ac.in/'],
    ranking: 1,
    tuition: 3000,
  },
  {
    name: 'Indian Institute of Technology Delhi',
    country: 'India',
    city: 'New Delhi',
    domains: ['iitd.ac.in'],
    web_pages: ['https://home.iitd.ac.in/'],
    ranking: 2,
    tuition: 3000,
  },
  {
    name: 'Indian Institute of Science',
    country: 'India',
    city: 'Bangalore',
    domains: ['iisc.ac.in'],
    web_pages: ['https://www.iisc.ac.in/'],
    ranking: 3,
    tuition: 2500,
  },
];
