export const westernUniversities = [
  {
    name: 'Harvard University',
    country: 'United States',
    city: 'Cambridge, MA',
    domains: ['harvard.edu'],
    web_pages: ['https://www.harvard.edu/'],
    ranking: 1,
    tuition: 55000,
  },
  {
    name: 'Massachusetts Institute of Technology',
    country: 'United States',
    city: 'Cambridge, MA',
    domains: ['mit.edu'],
    web_pages: ['https://www.mit.edu/'],
    ranking: 2,
    tuition: 57000,
  },
  {
    name: 'Stanford University',
    country: 'United States',
    city: 'Stanford, CA',
    domains: ['stanford.edu'],
    web_pages: ['https://www.stanford.edu/'],
    ranking: 3,
    tuition: 56000,
  },
  {
    name: 'Yale University',
    country: 'United States',
    city: 'New Haven, CT',
    domains: ['yale.edu'],
    web_pages: ['https://www.yale.edu/'],
    ranking: 4,
    tuition: 62000,
  },
  {
    name: 'Princeton University',
    country: 'United States',
    city: 'Princeton, NJ',
    domains: ['princeton.edu'],
    web_pages: ['https://www.princeton.edu/'],
    ranking: 5,
    tuition: 57000,
  },
  {
    name: 'University of Pennsylvania',
    country: 'United States',
    city: 'Philadelphia, PA',
    domains: ['upenn.edu'],
    web_pages: ['https://www.upenn.edu/'],
    ranking: 6,
    tuition: 63000,
  },
  {
    name: 'California Institute of Technology',
    country: 'United States',
    city: 'Pasadena, CA',
    domains: ['caltech.edu'],
    web_pages: ['https://www.caltech.edu/'],
    ranking: 7,
    tuition: 58000,
  },
  {
    name: 'Johns Hopkins University',
    country: 'United States',
    city: 'Baltimore, MD',
    domains: ['jhu.edu'],
    web_pages: ['https://www.jhu.edu/'],
    ranking: 8,
    tuition: 60000,
  },
  {
    name: 'Northwestern University',
    country: 'United States',
    city: 'Evanston, IL',
    domains: ['northwestern.edu'],
    web_pages: ['https://www.northwestern.edu/'],
    ranking: 9,
    tuition: 61000,
  },
  {
    name: 'Duke University',
    country: 'United States',
    city: 'Durham, NC',
    domains: ['duke.edu'],
    web_pages: ['https://www.duke.edu/'],
    ranking: 10,
    tuition: 62000,
  },
  {
    name: 'University of California Los Angeles',
    country: 'United States',
    city: 'Los Angeles, CA',
    domains: ['ucla.edu'],
    web_pages: ['https://www.ucla.edu/'],
    ranking: 11,
    tuition: 45000,
  },
  {
    name: 'University of California Berkeley',
    country: 'United States',
    city: 'Berkeley, CA',
    domains: ['berkeley.edu'],
    web_pages: ['https://www.berkeley.edu/'],
    ranking: 12,
    tuition: 44000,
  },
  {
    name: 'Columbia University',
    country: 'United States',
    city: 'New York, NY',
    domains: ['columbia.edu'],
    web_pages: ['https://www.columbia.edu/'],
    ranking: 13,
    tuition: 64000,
  },
  {
    name: 'University of Chicago',
    country: 'United States',
    city: 'Chicago, IL',
    domains: ['uchicago.edu'],
    web_pages: ['https://www.uchicago.edu/'],
    ranking: 14,
    tuition: 62000,
  },
  {
    name: 'Cornell University',
    country: 'United States',
    city: 'Ithaca, NY',
    domains: ['cornell.edu'],
    web_pages: ['https://www.cornell.edu/'],
    ranking: 15,
    tuition: 63000,
  },
  {
    name: 'Brown University',
    country: 'United States',
    city: 'Providence, RI',
    domains: ['brown.edu'],
    web_pages: ['https://www.brown.edu/'],
    ranking: 16,
    tuition: 64000,
  },
  {
    name: 'Dartmouth College',
    country: 'United States',
    city: 'Hanover, NH',
    domains: ['dartmouth.edu'],
    web_pages: ['https://www.dartmouth.edu/'],
    ranking: 17,
    tuition: 62000,
  },
  {
    name: 'New York University',
    country: 'United States',
    city: 'New York, NY',
    domains: ['nyu.edu'],
    web_pages: ['https://www.nyu.edu/'],
    ranking: 18,
    tuition: 58000,
  },
  {
    name: 'University of Michigan',
    country: 'United States',
    city: 'Ann Arbor, MI',
    domains: ['umich.edu'],
    web_pages: ['https://www.umich.edu/'],
    ranking: 19,
    tuition: 52000,
  },
  {
    name: 'Carnegie Mellon University',
    country: 'United States',
    city: 'Pittsburgh, PA',
    domains: ['cmu.edu'],
    web_pages: ['https://www.cmu.edu/'],
    ranking: 20,
    tuition: 59000,
  },
  {
    name: 'University of Oxford',
    country: 'United Kingdom',
    city: 'Oxford',
    domains: ['ox.ac.uk'],
    web_pages: ['https://www.ox.ac.uk/'],
    ranking: 1,
    tuition: 35000,
  },
  {
    name: 'University of Cambridge',
    country: 'United Kingdom',
    city: 'Cambridge',
    domains: ['cam.ac.uk'],
    web_pages: ['https://www.cam.ac.uk/'],
    ranking: 2,
    tuition: 33000,
  },
  {
    name: 'Imperial College London',
    country: 'United Kingdom',
    city: 'London',
    domains: ['imperial.ac.uk'],
    web_pages: ['https://www.imperial.ac.uk/'],
    ranking: 3,
    tuition: 38000,
  },
  {
    name: 'London School of Economics',
    country: 'United Kingdom',
    city: 'London',
    domains: ['lse.ac.uk'],
    web_pages: ['https://www.lse.ac.uk/'],
    ranking: 4,
    tuition: 34000,
  },
  {
    name: 'University College London',
    country: 'United Kingdom',
    city: 'London',
    domains: ['ucl.ac.uk'],
    web_pages: ['https://www.ucl.ac.uk/'],
    ranking: 5,
    tuition: 32000,
  },
  {
    name: "King's College London",
    country: 'United Kingdom',
    city: 'London',
    domains: ['kcl.ac.uk'],
    web_pages: ['https://www.kcl.ac.uk/'],
    ranking: 6,
    tuition: 30000,
  },
  {
    name: 'University of Edinburgh',
    country: 'United Kingdom',
    city: 'Edinburgh',
    domains: ['ed.ac.uk'],
    web_pages: ['https://www.ed.ac.uk/'],
    ranking: 7,
    tuition: 28000,
  },
  {
    name: 'University of Manchester',
    country: 'United Kingdom',
    city: 'Manchester',
    domains: ['manchester.ac.uk'],
    web_pages: ['https://www.manchester.ac.uk/'],
    ranking: 8,
    tuition: 26000,
  },
  {
    name: 'University of Warwick',
    country: 'United Kingdom',
    city: 'Coventry',
    domains: ['warwick.ac.uk'],
    web_pages: ['https://www.warwick.ac.uk/'],
    ranking: 9,
    tuition: 27000,
  },
  {
    name: 'University of Bristol',
    country: 'United Kingdom',
    city: 'Bristol',
    domains: ['bristol.ac.uk'],
    web_pages: ['https://www.bristol.ac.uk/'],
    ranking: 10,
    tuition: 25000,
  },
];
