export const pricingPlans = [
  {
    title: 'Basic',
    price: 0,
    currency: 'USD',
    frequency: '/month',
    description: 'Boost enrollment using AI and data analytics',
    features: [
      'University Microsite',
      'Smart Chatbot',
      'Marketing and Outreach',
      'Access to iSchoolConnect Events',
      'Nurturing and conversion campaigns',
    ],
    cta: 'Register',
    forInstitutions: true,
  },
  {
    title: 'Essential',
    price: 2000,
    currency: 'USD',
    frequency: '/month',
    description: 'Scale international student admissions with ease',
    features: [
      'Access to 2 million + prospects',
      'Advanced chatbot',
      'Marketing Enablement Module',
      'Sales Enablement Module',
      'In - Country Representation',
    ],
    cta: 'Register',
    forInstitutions: true,
  },
  {
    title: 'Premium',
    price: 5000,
    currency: 'USD',
    frequency: '/yearly',
    description: 'Transform your brand experience end-to-end',
    features: [
      'Admissions Enablement Module',
      'Graduate Potential Predictor',
      'Employment Potential Predictor',
      'Dedicated In - Country Advisors',
      'Human Success Coaches',
    ],
    cta: 'Register',
    forInstitutions: true,
  },
];
