const initialForm = {
  fullName: '',
  lastName: '',
  email: '',
  targetCountry: '',
  degreeLevel: '',
  programArea: '',
  fieldOfStudy: '',
  scoreType: 'CGPA_10',
  scoreValue: '',
  boardOrUniversity: '',
  englishTest: 'NOT_TAKEN',
  englishScore: '',
  aptitudeTest: 'NOT_REQUIRED',
  aptitudeScore: '',
  budgetCurrency: 'INR',
  budgetAmount: '',
  budgetIncludes: 'tuition_living',
  fundingPlan: '',
  targetIntake: '',
  applicationStage: '',
  deadlineUrgency: '',
  workExperienceMonths: '',
  gpa: '',
  testScores: '',
  budget: '',
  timeline: '',
  workExperience: '',
  extracurriculars: '',
  notes: '',
};
export default initialForm;
