export const pricingPlans = [
  {
    title: 'Basic Package (Free)',
    price: 0,
    currency: 'INR',
    frequency: '/free',
    features: [
      'Complimentary initial counseling session to explore your study abroad goals',
      'Essential university and course recommendations to get you started',
      'Limited student portal access for 20 days',
      'Up to 2 personalized counseling sessions',
      'Support through chat and email for general queries',
      'Assistance with applications to up to 2 universities',
    ],
    cta: 'Enroll',
    forInstitutions: false,
  },
  {
    title: 'Advantage Package',
    price: 14999,
    currency: 'INR',
    frequency: '/One-Time Payment',
    features: [
      'Expert personalized career and academic counseling tailored to your goals',
      'AI + human-curated university and course recommendations',
      'Full access to the student portal with tracking until your chosen intake',
      'Ongoing support from a dedicated counselor with timely responses',
      'Comprehensive application assistance for up to 6 universities',
      'Professional SOP, essay, and resume review with detailed feedback',
      'Coaching for university and visa interview preparation',
      'Guidance to secure scholarships and financial aid',
      'Access to exclusive webinars and interactive sessions',
    ],
    cta: 'Enroll',
    forInstitutions: false,
  },
];
