const DEFAULT_TITLE = 'Plan My Admission | Study Abroad & Admissions Guidance';
const DEFAULT_DESCRIPTION =
  'Plan My Admission offers expert overseas education consulting with personalized university admissions guidance, student visa support, and AI-powered tools to simplify your study abroad journey.';

export const ROUTE_META = {
  '/': {
    title: DEFAULT_TITLE,
    description: DEFAULT_DESCRIPTION,
    sitemap: {
      changeFrequency: 'weekly',
      priority: 1.0,
    },
  },
  '/contact': {
    title: 'Contact Plan My Admission | Study Abroad Help',
    description:
      'Questions about studying abroad? Contact Plan My Admission for personalized guidance on colleges, courses, exams, and applications.',
    sitemap: {
      changeFrequency: 'yearly',
      priority: 0.6,
    },
  },
  '/about': {
    title: 'About Plan My Admission | Study Abroad Experts',
    description:
      'Meet the team behind your study abroad journey. Learn about our mission and commitment to expert admissions guidance.',
    sitemap: {
      changeFrequency: 'yearly',
      priority: 0.6,
    },
  },
  '/pricing': {
    title: 'Plan My Admission Pricing | Plans & Packages',
    description:
      'Explore Plan My Admission pricing and plans designed for students preparing for study abroad.',
    sitemap: {
      changeFrequency: 'monthly',
      priority: 0.8,
    },
  },
  '/for-institutions': {
    title: 'Plan My Admission for Institutions',
    description:
      'Scale international student admissions with Plan My Admission’s AI-powered tools and counseling support.',
    sitemap: {
      changeFrequency: 'monthly',
      priority: 0.8,
    },
  },
  '/terms&conditions': {
    title: 'Terms & Conditions | Plan My Admission',
    description:
      'Read the terms and conditions for using Plan My Admission services and website.',
    sitemap: false,
  },
  '/terms-and-conditions': {
    title: 'Terms & Conditions | Plan My Admission',
    description:
      'Read the terms and conditions for using Plan My Admission services and website.',
    sitemap: {
      changeFrequency: 'yearly',
      priority: 0.4,
    },
  },
  '/privacy-policy': {
    title: 'Privacy Policy | Plan My Admission',
    description:
      'Learn how Plan My Admission collects, uses, and safeguards your information.',
    sitemap: {
      changeFrequency: 'yearly',
      priority: 0.4,
    },
  },
  '/how-it-works': {
    title: 'How It Works | Plan My Admission',
    description:
      'Understand how Plan My Admission guides you from university selection to admission.',
    sitemap: {
      changeFrequency: 'monthly',
      priority: 0.8,
    },
  },
  '/explore': {
    title: 'Explore Universities | Plan My Admission',
    description:
      'Discover universities, courses, and destinations for your study abroad plans.',
    sitemap: {
      changeFrequency: 'weekly',
      priority: 0.8,
    },
  },
  '/ai-university-matchmaker': {
    title: 'AI University Matchmaker | Plan My Admission',
    description:
      'Get AI-powered university matches based on your profile, budget, intake, and study goals.',
    sitemap: {
      changeFrequency: 'weekly',
      priority: 0.9,
    },
  },
  '/explore/university': {
    title: 'University Explorer | Plan My Admission',
    description:
      'Explore detailed university profiles and programs to plan your admissions.',
    sitemap: {
      changeFrequency: 'weekly',
      priority: 0.7,
    },
  },
  '/blogs': {
    title: 'Plan My Admission Blog | Study Abroad Insights',
    description:
      'Read the latest study abroad insights, tips, and updates from Plan My Admission.',
    sitemap: {
      changeFrequency: 'weekly',
      priority: 0.8,
    },
  },
  '/recommendations': {
    title: 'Recommendations | Plan My Admission',
    description:
      'View personalized university recommendations based on your profile and goals.',
    sitemap: {
      changeFrequency: 'weekly',
      priority: 0.7,
    },
  },
  '/admin': {
    title: 'Admin Dashboard | Plan My Admission',
    description:
      'Internal admin dashboard for lead management and operational workflows.',
    noIndex: true,
    sitemap: false,
  },
  '/admin/login': {
    title: 'Admin Login | Plan My Admission',
    description: 'Internal admin sign in for the Plan My Admission team.',
    noIndex: true,
    sitemap: false,
  },
  '/admin/leads': {
    title: 'Admin Leads | Plan My Admission',
    description:
      'Internal admin view for managing leads generated by AI matchmaker submissions.',
    noIndex: true,
    sitemap: false,
  },
  '/admin/blogs': {
    title: 'Admin Blogs | Plan My Admission',
    description:
      'Internal admin view for publishing blog posts and managing article metadata.',
    noIndex: true,
    sitemap: false,
  },
};
