export const pricingPlans = [
  {
    title: "Basic",
    price: 0,
    currency: "INR",
    frequency: "/month",
    // description: "Lorem ipsum, dite",
    features: [
      "No Assisted Recommendations",
      "Initial Counselling",
      "Essay and SOP Grading Tool",
      "Visa/MBA Interview Tool",
    ],
    cta: "Resgister",
    forInstitutions: false,
  },
  {
    title: "Essential",
    price: 1000,
    currency: "INR",
    frequency: "/month",
    // description: "Lorem ipsum, dite",
    features: [
      "10 Assisted Recommendations",
      "Dedicated Counselling Mentor",
      "Basic Essay and SOP Grading Tool",
      "Basic Visa / MBA Interview Tool",
      "On - demand Test Preparation",
      "6 Applications Allowed",
    ],
    cta: "Resgister",
    forInstitutions: false,
  },
  {
    title: "Premium",
    price: 2000,
    currency: "INR",
    frequency: "/month",
    // description: "Lorem ipsum, dite",
    features: [
      "10 Assisted Recommendations",
      "Dedicated Counselling Mentor",
      "Advanced Essay and SOP Grading Tool",
      "Advanced Visa / MBA Interview Tool",
      "On - demand Test Preparation",
      "10 Applications Allowed",
    ],
    cta: "Resgister",
    forInstitutions: false,
  },
];

// {
//   title: "Premium",
//   price: 5000,
//   currency: "USD",
//   frequency: "/yearly",
//   description: "Lorem ipsum, dite",
//   features: [
//     "10 Assisted Recommandation",
//     "6 Application allowed",
//     "No Assisted Recommendations",
//     "Initial Counselling",
//     "Essay and SOP Grading Tool",
//     "Visa/MBA Interview Tool",
//   ],
//   cta: "Resgister",
//   forInstitutions: false,
// },
