export const exchangeRate = 84;

export const apiConfig = {
  debounceDelay: 300,
  timeout: 8000,
  openalex: 'https://api.openalex.org/institutions?search=',
  hipolabs: 'https://universities.hipolabs.com/search?name=',
  corsProxy: 'https://api.allorigins.win/get?url=',
};

export const universityAbbreviations = {
  mit: 'massachusetts institute of technology',
  jhu: 'johns hopkins university',
  nyu: 'new york university',
  ucla: 'university of california los angeles',
  'uc berkeley': 'university of california berkeley',
  berkeley: 'university of california berkeley',
  caltech: 'california institute of technology',
  cmu: 'carnegie mellon university',
  harvard: 'harvard university',
  stanford: 'stanford university',
  yale: 'yale university',
  princeton: 'princeton university',
  oxford: 'university of oxford',
  cambridge: 'university of cambridge',
  imperial: 'imperial college london',
  ucl: 'university college london',
  kcl: 'kings college london',
  lse: 'london school of economics',
  toronto: 'university of toronto',
  ubc: 'university of british columbia',
  mcgill: 'mcgill university',
  anu: 'australian national university',
  unsw: 'university of new south wales',
  nus: 'national university of singapore',
  ntu: 'nanyang technological university',
  eth: 'eth zurich',
  tum: 'technical university of munich',
};

export const commonMisspellings = {
  'john hopkins': 'johns hopkins',
  massachusets: 'massachusetts',
  pennsylvannia: 'pennsylvania',
  berkley: 'berkeley',
  californa: 'california',
  washingon: 'washington',
  universtiy: 'university',
  univeristy: 'university',
  colege: 'college',
  insitute: 'institute',
  tecnology: 'technology',
  standford: 'stanford',
  havard: 'harvard',
  oxfort: 'oxford',
  cambrige: 'cambridge',
};

export const studyLevels = [
  { value: "Bachelor's", label: "Bachelor's Degree" },
  { value: "Master's", label: "Master's Degree" },
  { value: 'PhD', label: 'PhD/Doctorate' },
  { value: 'Certificate', label: 'Certificate Program' },
];

export const embeddedUniversities = [
  {
    name: 'Harvard University',
    country: 'United States',
    city: 'Cambridge, MA',
    domains: ['harvard.edu'],
    web_pages: ['https://www.harvard.edu/'],
    ranking: 1,
    tuition: 55000,
  },
  {
    name: 'Massachusetts Institute of Technology',
    country: 'United States',
    city: 'Cambridge, MA',
    domains: ['mit.edu'],
    web_pages: ['https://www.mit.edu/'],
    ranking: 2,
    tuition: 57000,
  },
  {
    name: 'Stanford University',
    country: 'United States',
    city: 'Stanford, CA',
    domains: ['stanford.edu'],
    web_pages: ['https://www.stanford.edu/'],
    ranking: 3,
    tuition: 56000,
  },
  {
    name: 'Yale University',
    country: 'United States',
    city: 'New Haven, CT',
    domains: ['yale.edu'],
    web_pages: ['https://www.yale.edu/'],
    ranking: 4,
    tuition: 62000,
  },
  {
    name: 'Princeton University',
    country: 'United States',
    city: 'Princeton, NJ',
    domains: ['princeton.edu'],
    web_pages: ['https://www.princeton.edu/'],
    ranking: 5,
    tuition: 57000,
  },
  {
    name: 'University of Pennsylvania',
    country: 'United States',
    city: 'Philadelphia, PA',
    domains: ['upenn.edu'],
    web_pages: ['https://www.upenn.edu/'],
    ranking: 6,
    tuition: 63000,
  },
  {
    name: 'California Institute of Technology',
    country: 'United States',
    city: 'Pasadena, CA',
    domains: ['caltech.edu'],
    web_pages: ['https://www.caltech.edu/'],
    ranking: 7,
    tuition: 58000,
  },
  {
    name: 'Johns Hopkins University',
    country: 'United States',
    city: 'Baltimore, MD',
    domains: ['jhu.edu'],
    web_pages: ['https://www.jhu.edu/'],
    ranking: 8,
    tuition: 60000,
  },
  {
    name: 'Northwestern University',
    country: 'United States',
    city: 'Evanston, IL',
    domains: ['northwestern.edu'],
    web_pages: ['https://www.northwestern.edu/'],
    ranking: 9,
    tuition: 61000,
  },
  {
    name: 'Duke University',
    country: 'United States',
    city: 'Durham, NC',
    domains: ['duke.edu'],
    web_pages: ['https://www.duke.edu/'],
    ranking: 10,
    tuition: 62000,
  },
  {
    name: 'University of California Los Angeles',
    country: 'United States',
    city: 'Los Angeles, CA',
    domains: ['ucla.edu'],
    web_pages: ['https://www.ucla.edu/'],
    ranking: 11,
    tuition: 45000,
  },
  {
    name: 'University of California Berkeley',
    country: 'United States',
    city: 'Berkeley, CA',
    domains: ['berkeley.edu'],
    web_pages: ['https://www.berkeley.edu/'],
    ranking: 12,
    tuition: 44000,
  },
  {
    name: 'Columbia University',
    country: 'United States',
    city: 'New York, NY',
    domains: ['columbia.edu'],
    web_pages: ['https://www.columbia.edu/'],
    ranking: 13,
    tuition: 64000,
  },
  {
    name: 'University of Chicago',
    country: 'United States',
    city: 'Chicago, IL',
    domains: ['uchicago.edu'],
    web_pages: ['https://www.uchicago.edu/'],
    ranking: 14,
    tuition: 62000,
  },
  {
    name: 'Cornell University',
    country: 'United States',
    city: 'Ithaca, NY',
    domains: ['cornell.edu'],
    web_pages: ['https://www.cornell.edu/'],
    ranking: 15,
    tuition: 63000,
  },
  {
    name: 'Brown University',
    country: 'United States',
    city: 'Providence, RI',
    domains: ['brown.edu'],
    web_pages: ['https://www.brown.edu/'],
    ranking: 16,
    tuition: 64000,
  },
  {
    name: 'Dartmouth College',
    country: 'United States',
    city: 'Hanover, NH',
    domains: ['dartmouth.edu'],
    web_pages: ['https://www.dartmouth.edu/'],
    ranking: 17,
    tuition: 62000,
  },
  {
    name: 'New York University',
    country: 'United States',
    city: 'New York, NY',
    domains: ['nyu.edu'],
    web_pages: ['https://www.nyu.edu/'],
    ranking: 18,
    tuition: 58000,
  },
  {
    name: 'University of Michigan',
    country: 'United States',
    city: 'Ann Arbor, MI',
    domains: ['umich.edu'],
    web_pages: ['https://www.umich.edu/'],
    ranking: 19,
    tuition: 52000,
  },
  {
    name: 'Carnegie Mellon University',
    country: 'United States',
    city: 'Pittsburgh, PA',
    domains: ['cmu.edu'],
    web_pages: ['https://www.cmu.edu/'],
    ranking: 20,
    tuition: 59000,
  },
  {
    name: 'University of Oxford',
    country: 'United Kingdom',
    city: 'Oxford',
    domains: ['ox.ac.uk'],
    web_pages: ['https://www.ox.ac.uk/'],
    ranking: 1,
    tuition: 35000,
  },
  {
    name: 'University of Cambridge',
    country: 'United Kingdom',
    city: 'Cambridge',
    domains: ['cam.ac.uk'],
    web_pages: ['https://www.cam.ac.uk/'],
    ranking: 2,
    tuition: 33000,
  },
  {
    name: 'Imperial College London',
    country: 'United Kingdom',
    city: 'London',
    domains: ['imperial.ac.uk'],
    web_pages: ['https://www.imperial.ac.uk/'],
    ranking: 3,
    tuition: 38000,
  },
  {
    name: 'London School of Economics',
    country: 'United Kingdom',
    city: 'London',
    domains: ['lse.ac.uk'],
    web_pages: ['https://www.lse.ac.uk/'],
    ranking: 4,
    tuition: 34000,
  },
  {
    name: 'University College London',
    country: 'United Kingdom',
    city: 'London',
    domains: ['ucl.ac.uk'],
    web_pages: ['https://www.ucl.ac.uk/'],
    ranking: 5,
    tuition: 32000,
  },
  {
    name: "King's College London",
    country: 'United Kingdom',
    city: 'London',
    domains: ['kcl.ac.uk'],
    web_pages: ['https://www.kcl.ac.uk/'],
    ranking: 6,
    tuition: 30000,
  },
  {
    name: 'University of Edinburgh',
    country: 'United Kingdom',
    city: 'Edinburgh',
    domains: ['ed.ac.uk'],
    web_pages: ['https://www.ed.ac.uk/'],
    ranking: 7,
    tuition: 28000,
  },
  {
    name: 'University of Manchester',
    country: 'United Kingdom',
    city: 'Manchester',
    domains: ['manchester.ac.uk'],
    web_pages: ['https://www.manchester.ac.uk/'],
    ranking: 8,
    tuition: 26000,
  },
  {
    name: 'University of Warwick',
    country: 'United Kingdom',
    city: 'Coventry',
    domains: ['warwick.ac.uk'],
    web_pages: ['https://www.warwick.ac.uk/'],
    ranking: 9,
    tuition: 27000,
  },
  {
    name: 'University of Bristol',
    country: 'United Kingdom',
    city: 'Bristol',
    domains: ['bristol.ac.uk'],
    web_pages: ['https://www.bristol.ac.uk/'],
    ranking: 10,
    tuition: 25000,
  },
  {
    name: 'University of Toronto',
    country: 'Canada',
    city: 'Toronto, ON',
    domains: ['utoronto.ca'],
    web_pages: ['https://www.utoronto.ca/'],
    ranking: 1,
    tuition: 32000,
  },
  {
    name: 'University of British Columbia',
    country: 'Canada',
    city: 'Vancouver, BC',
    domains: ['ubc.ca'],
    web_pages: ['https://www.ubc.ca/'],
    ranking: 2,
    tuition: 30000,
  },
  {
    name: 'McGill University',
    country: 'Canada',
    city: 'Montreal, QC',
    domains: ['mcgill.ca'],
    web_pages: ['https://www.mcgill.ca/'],
    ranking: 3,
    tuition: 28000,
  },
  {
    name: 'University of Melbourne',
    country: 'Australia',
    city: 'Melbourne, VIC',
    domains: ['unimelb.edu.au'],
    web_pages: ['https://www.unimelb.edu.au/'],
    ranking: 1,
    tuition: 45000,
  },
  {
    name: 'University of Sydney',
    country: 'Australia',
    city: 'Sydney, NSW',
    domains: ['sydney.edu.au'],
    web_pages: ['https://www.sydney.edu.au/'],
    ranking: 2,
    tuition: 47000,
  },
  {
    name: 'Australian National University',
    country: 'Australia',
    city: 'Canberra, ACT',
    domains: ['anu.edu.au'],
    web_pages: ['https://www.anu.edu.au/'],
    ranking: 3,
    tuition: 42000,
  },
  {
    name: 'ETH Zurich',
    country: 'Switzerland',
    city: 'Zurich',
    domains: ['ethz.ch'],
    web_pages: ['https://ethz.ch/en.html'],
    ranking: 1,
    tuition: 1500,
  },
  {
    name: 'Technical University of Munich',
    country: 'Germany',
    city: 'Munich',
    domains: ['tum.de'],
    web_pages: ['https://www.tum.de/en/'],
    ranking: 1,
    tuition: 0,
  },
  {
    name: 'University of Amsterdam',
    country: 'Netherlands',
    city: 'Amsterdam',
    domains: ['uva.nl'],
    web_pages: ['https://www.uva.nl/en'],
    ranking: 1,
    tuition: 12000,
  },
  {
    name: 'Sorbonne University',
    country: 'France',
    city: 'Paris',
    domains: ['sorbonne-universite.fr'],
    web_pages: ['https://www.sorbonne-universite.fr/en'],
    ranking: 1,
    tuition: 3000,
  },
  {
    name: 'National University of Singapore',
    country: 'Singapore',
    city: 'Singapore',
    domains: ['nus.edu.sg'],
    web_pages: ['https://www.nus.edu.sg/'],
    ranking: 1,
    tuition: 38000,
  },
  {
    name: 'University of Tokyo',
    country: 'Japan',
    city: 'Tokyo',
    domains: ['u-tokyo.ac.jp'],
    web_pages: ['https://www.u-tokyo.ac.jp/en/'],
    ranking: 1,
    tuition: 25000,
  },
  {
    name: 'Peking University',
    country: 'China',
    city: 'Beijing',
    domains: ['pku.edu.cn'],
    web_pages: ['https://english.pku.edu.cn/'],
    ranking: 1,
    tuition: 15000,
  },
  {
    name: 'Seoul National University',
    country: 'South Korea',
    city: 'Seoul',
    domains: ['snu.ac.kr'],
    web_pages: ['https://en.snu.ac.kr/'],
    ranking: 1,
    tuition: 12000,
  },
  {
    name: 'Indian Institute of Technology Bombay',
    country: 'India',
    city: 'Mumbai',
    domains: ['iitb.ac.in'],
    web_pages: ['https://www.iitb.ac.in/'],
    ranking: 1,
    tuition: 3000,
  },
  {
    name: 'Indian Institute of Technology Delhi',
    country: 'India',
    city: 'New Delhi',
    domains: ['iitd.ac.in'],
    web_pages: ['https://home.iitd.ac.in/'],
    ranking: 2,
    tuition: 3000,
  },
  {
    name: 'Indian Institute of Science',
    country: 'India',
    city: 'Bangalore',
    domains: ['iisc.ac.in'],
    web_pages: ['https://www.iisc.ac.in/'],
    ranking: 3,
    tuition: 2500,
  },
];

export const eligibilityRequirements = {
  "Bachelor's": { minGpa: 2.5, minIelts: 6.0, minToefl: 80 },
  "Master's": { minGpa: 3.0, minIelts: 6.5, minToefl: 90 },
  PhD: { minGpa: 3.3, minIelts: 7.0, minToefl: 100 },
  Certificate: { minGpa: 2.0, minIelts: 5.5, minToefl: 70 },
};
